### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by ghost** [DeltaNeverUsed/reddit-place-script-2022#1]

**Comment by ghost** [comment]
just verifying my accounts

**Comment by DeltaNeverUsed** [comment]
my version doesn't wait for the account to be able to place, i'm too lazy to implement that at the moment, so it tries to place one down every 5 minutes, so only email verified accounts won't get rate limited

**Comment by ghost** [comment]
seems like its working

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/12817965/161397831-08ca9a46-a7ea-43d7-a84c-def36c4a4979.png)
got this error but not sure why

**Comment by DeltaNeverUsed** [comment]
Could you send the full thing?

**Comment by ghost** [comment]
it works as its supposed to until: 
```
refreshing access token for Stunning_Captain_305 ...
Traceback (most recent call last):
  File "D:\David\Documents\RPlace\reddit-place-script-2022-Delta-s-Edition-main\main.py", line 416, in <module>
    get_valid_auth(name)
  File "D:\David\Documents\RPlace\reddit-place-script-2022-Delta-s-Edition-main\main.py", line 208, in get_valid_auth
    accounts[name]['access_token'] = response_data["access_token"]
KeyError: 'access_token'

Process finished with exit code 1
```

**Comment by DeltaNeverUsed** [comment]
your account info is probably incorrect

**Comment by ghost** [comment]
i think the app secret was incorrect

**Comment by ghost** [comment]
is it possible to preemptively create a branch that has the code for if they double the board again?

**Comment by DeltaNeverUsed** [comment]
Yes, but i am unsure of how they'll do that, but it should be an easy change in the current one, i already did add some support for it

**Comment by ghost** [comment]
okay cool, it'll be cool to get in on it early if it does double.
