### ISSUE TITLE
Crash from connection loss

### ISSUE THREAD

**Issue by thecosmicskye** [DeltaNeverUsed/reddit-place-script-2022#19]
```
Traceback (most recent call last):
  File "reddit-place-script-2022-Delta-s-Edition\main.py", line 521, in <module>
    place_pixel()
  File "reddit-place-script-2022-Delta-s-Edition\main.py", line 478, in place_pixel
    board = get_board(list(accounts.values())[0]['access_token'])
  File "reddit-place-script-2022-Delta-s-Edition\main.py", line 350, in get_board
    temp = json.loads(ws.recv())
  File "venv\lib\site-packages\websocket\_core.py", line 357, in recv
    opcode, data = self.recv_data()
  File "venv\lib\site-packages\websocket\_core.py", line 380, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "venv\lib\site-packages\websocket\_core.py", line 401, in recv_data_frame
    frame = self.recv_frame()
  File "venv\lib\site-packages\websocket\_core.py", line 440, in recv_frame
    return self.frame_buffer.recv_frame()
  File "venv\lib\site-packages\websocket\_abnf.py", line 338, in recv_frame
    self.recv_header()
  File "venv\lib\site-packages\websocket\_abnf.py", line 294, in recv_header
    header = self.recv_strict(2)
  File "venv\lib\site-packages\websocket\_abnf.py", line 373, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "venv\lib\site-packages\websocket\_core.py", line 524, in _recv
    return recv(self.sock, bufsize)
  File "reddit-place-script-2022-Delta-s-Edition\venv\lib\site-packages\websocket\_socket.py", line 122, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.

Process finished with exit code 1
```

This probably should be wrapped in some sort of try loop

**Comment by DeltaNeverUsed** [comment]
i'll look into it
