### ISSUE TITLE
error on latest version

### ISSUE THREAD

**Issue by ghost** [DeltaNeverUsed/reddit-place-script-2022#8]
I keep getting this error.

```
timed out
ERROR:root:[ignored]
Traceback (most recent call last):
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\cell_socket.py", line 63, in connect
    self._socket.connect((self._router.ip, self._router.or_port))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 1342, in connect
    self._real_connect(addr, False)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 1329, in _real_connect
    super().connect(addr)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\utils.py", line 79, in newfn
    return func(*args, **kwargs)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 235, in renew
    raw_string = self.download_consensus(prev_hash)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 183, in newfn
    return func(*args, **kwargs)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 390, in download_consensus
    with self._get_dir_client() as dir_client:
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 375, in _get_dir_client
    self._dir_guard, self._dir_circuit = self._create_dir_circuit(purpose='Internal dir client')
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 365, in _create_dir_circuit
    guard = TorGuard(router, purpose=purpose)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\guard.py", line 66, in __init__
    self.__tor_socket.connect()
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\cell_socket.py", line 69, in connect
    raise TorSocketConnectError(e)
torpy.cell_socket.TorSocketConnectError: timed out
WARNING:torpy.utils:Retry with another router...
ERROR:torpy.cell_socket:timed out
ERROR:root:[ignored]
Traceback (most recent call last):
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\cell_socket.py", line 63, in connect
    self._socket.connect((self._router.ip, self._router.or_port))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 1342, in connect
    self._real_connect(addr, False)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 1329, in _real_connect
    super().connect(addr)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\utils.py", line 79, in newfn
    return func(*args, **kwargs)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 235, in renew
    raw_string = self.download_consensus(prev_hash)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 183, in newfn
    return func(*args, **kwargs)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 390, in download_consensus
    with self._get_dir_client() as dir_client:
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 375, in _get_dir_client
    self._dir_guard, self._dir_circuit = self._create_dir_circuit(purpose='Internal dir client')
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 365, in _create_dir_circuit
    guard = TorGuard(router, purpose=purpose)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\guard.py", line 66, in __init__
    self.__tor_socket.connect()
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\cell_socket.py", line 69, in connect
    raise TorSocketConnectError(e)
torpy.cell_socket.TorSocketConnectError: timed out
WARNING:torpy.utils:Retry with another router...
ERROR:torpy.cell_socket:Cell type (84) not found
ERROR:root:[ignored]
Traceback (most recent call last):
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\cell_socket.py", line 66, in connect
    handshake.initiate()
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\cell_socket.py", line 212, in initiate
    self.tor_protocol.version = self._retrieve_versions()
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\cell_socket.py", line 237, in _retrieve_versions
    cell = self.tor_socket.recv_cell()
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\cell_socket.py", line 98, in recv_cell
    for cell in self._build_next_cell():
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\cell_socket.py", line 114, in _build_next_cell
    self._next_len = self._cells_builder.send(send_buff)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\cell_socket.py", line 125, in _cells_builder_gen
    cell_type = TorCommands.get_by_num(command_num)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\cells.py", line 846, in get_by_num
    raise Exception('Cell type ({}) not found'.format(num))
Exception: Cell type (84) not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\utils.py", line 79, in newfn
    return func(*args, **kwargs)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 235, in renew
    raw_string = self.download_consensus(prev_hash)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 183, in newfn
    return func(*args, **kwargs)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 390, in download_consensus
    with self._get_dir_client() as dir_client:
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 375, in _get_dir_client
    self._dir_guard, self._dir_circuit = self._create_dir_circuit(purpose='Internal dir client')
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 365, in _create_dir_circuit
    guard = TorGuard(router, purpose=purpose)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\guard.py", line 66, in __init__
    self.__tor_socket.connect()
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\cell_socket.py", line 69, in connect
    raise TorSocketConnectError(e)
torpy.cell_socket.TorSocketConnectError: Cell type (84) not found
WARNING:torpy.utils:Retry with another router...
ERROR:root:[ignored]
Traceback (most recent call last):
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\cell_socket.py", line 66, in connect
    handshake.initiate()
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\cell_socket.py", line 212, in initiate
    self.tor_protocol.version = self._retrieve_versions()
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\cell_socket.py", line 237, in _retrieve_versions
    cell = self.tor_socket.recv_cell()
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\cell_socket.py", line 98, in recv_cell
    for cell in self._build_next_cell():
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\cell_socket.py", line 114, in _build_next_cell
    self._next_len = self._cells_builder.send(send_buff)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\cell_socket.py", line 125, in _cells_builder_gen
    cell_type = TorCommands.get_by_num(command_num)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\cells.py", line 846, in get_by_num
    raise Exception('Cell type ({}) not found'.format(num))
Exception: Cell type (84) not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\utils.py", line 79, in newfn
    return func(*args, **kwargs)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 235, in renew
    raw_string = self.download_consensus(prev_hash)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 183, in newfn
    return func(*args, **kwargs)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 390, in download_consensus
    with self._get_dir_client() as dir_client:
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 375, in _get_dir_client
    self._dir_guard, self._dir_circuit = self._create_dir_circuit(purpose='Internal dir client')
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 365, in _create_dir_circuit
    guard = TorGuard(router, purpose=purpose)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\guard.py", line 66, in __init__
    self.__tor_socket.connect()
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\cell_socket.py", line 69, in connect
    raise TorSocketConnectError(e)
torpy.cell_socket.TorSocketConnectError: Cell type (84) not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\utils.py", line 79, in newfn
    return func(*args, **kwargs)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\client.py", line 53, in get_guard
    guard_router = self._consensus.get_random_guard_node(by_flags)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 342, in get_random_guard_node
    return self.get_random_router(flags)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 337, in get_random_router
    routers = self.get_routers(flags, has_dir_port, with_renew)
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 319, in get_routers
    for onion_router in self.get_document(with_renew=with_renew).routers:
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\consesus.py", line 219, in get_document
    self.renew()
  File "C:\Users\david\.virtualenvs\reddit-place-script-2022-Delta-s-Edition-main\lib\site-packages\torpy\utils.py", line 101, in newfn
    time.sleep(total_delay)
KeyboardInterrupt
WARNING:torpy.utils:Retry with another guard...
WARNING:torpy.http.requests:Sending: POST https://gql-realtime-2.reddit.com/query

Process finished with exit code -1

```

**Comment by DeltaNeverUsed** [comment]
Honestly not quite sure why this happens

**Comment by ghost** [comment]
so no way to fix it? XD

**Comment by DeltaNeverUsed** [comment]
There probably is, but i probably wont
